server:
  port: 8763
  
spring:
  application:
    name: gsdd-admin-server
  output:
    ansi:
      enabled: always
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 5
    service-url:
      default-zone: http://localhost:8761/eureka
  
